load("@io_bazel_rules_scala//scala:scala.bzl", "scala_library")

java_library(
    name = "subpackage",
    srcs = glob([
        "*.java",
        "*.scala",
    ]),
    visibility = ["//visibility:public"],
)
